### ISSUE TITLE
Reviews Object

### ISSUE THREAD

**Issue by TheConnMan** [TheConnMan/ZwegersMel#15]
The fields I was thinking of having were:
- Title
- Content
- Date
- Reviewer

Is that enough for a review? You mentioned wanting to add in a photo. Do you think there will normally be a photo?

**Comment by zwegersmel** [comment]
Hey Brian,

That looks like great fields for the review. No, there won't be a photo
normally, that was just something I thought of adding in next to the
current review on the page (the woman sent a picture of her daughter
reading the book). I still have to ask if she would give me permission to
use the photo.

Hope you're enjoying a nice dinner!
Melanie

On Sun, Mar 1, 2015 at 4:48 PM, Brian Conn notifications@github.com wrote:

> Assigned #15 https://github.com/TheConnMan/ZwegersMel/issues/15 to
> @zwegersmel https://github.com/zwegersmel.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheConnMan/ZwegersMel/issues/15#event-244039753.

## 

_Melanie M Zwegers_

Children's Writer & Illustrator

www.melaniemzwegers.com

**Comment by TheConnMan** [comment]
Great, thanks.
