### ISSUE TITLE
All caps tab text

### ISSUE THREAD

**Issue by madjenjen** [TheConnMan/ZwegersMel#19]
On the Weebly site, the tab text is in all caps and smaller and more spaced apart, while the title of the page is bigger. Recommend making all caps.

Also the tab gray color is lighter.

**Comment by madjenjen** [comment]
In general, looks like all text is bigger on the Weebly site. Recommend making bigger on custom site.

**Comment by zwegersmel** [comment]
Yes, both of these issues would be nice to adjust. Thanks!
