### ISSUE TITLE
Add Photo Carousel To Book Page

### ISSUE THREAD

**Issue by TheConnMan** [TheConnMan/ZwegersMel#2]

**Comment by TheConnMan** [comment]
@zwegersmel The latest is up on dev, let me know if you like the colorbox I used. Also, if you send me titles for the images I can add them in.

**Comment by zwegersmel** [comment]
Hi Brian,

The photos look great on the dev site, thanks! I'm not sure what a colorbox
is, but whatever format you've chosen looks fine to me. I have decided to
change one of the sample pages--could you take out the "welcome" sign
picture and put the attached poem "fairy doors" as the first image? Also, I
am really curious as to how many people have been trafficking in the
website, and I remembered you saying you had a way to look up that
information. If you have it handy, can I see it?

Thank you so, so much, like always, for your generosity and help in this.
We've had some major sales and really successful Emerson visits!

Talk soon,
Melanie

On Sat, Mar 14, 2015 at 1:38 PM, Brian Conn notifications@github.com
wrote:

> @zwegersmel https://github.com/zwegersmel The latest is up on dev, let
> me know if you like the colorbox I used. Also, if you send me titles for
> the images I can add them in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheConnMan/ZwegersMel/issues/2#issuecomment-80626379.

## 

_Melanie M Zwegers_

Children's Writer & Illustrator

www.melaniemzwegers.com

**Comment by TheConnMan** [comment]
The attachment didn't come through because you responded to the GitHub comment email. Could you send it to my personal email? Call me when you get a chance and I'll show you the analytics.

The colorbox is just what that popup image container is called. Did you want titles on them, too?
