### ISSUE TITLE
New Event to Add

### ISSUE THREAD

**Issue by zwegersmel** [TheConnMan/ZwegersMel#23]
I wasn't sure if my adding a new event to the dev. site would be reflected in the final site or not, so I'm just putting in here in case! 

Could you please add this event in the correct chronological place:

Author Fair Book Booth
Saturday, March 28 2015, 1:00-3:00pm
Walldorf/Dunning Rooms, Main Level
Plymouth District Library,
223 S. Main Street, Plymouth

Thanks a bunch!

**Comment by TheConnMan** [comment]
The dev site and the main site are two different servers now. If you want
to make production changes you can add it to the non-dev site.

## 

_Brian C. Conn_

**Comment by zwegersmel** [comment]
Okay, how do I login in to the regular site? Sorry!

On Mon, Mar 2, 2015 at 11:44 AM, Brian Conn notifications@github.com
wrote:

> The dev site and the main site are two different servers now. If you want
> to make production changes you can add it to the non-dev site.
> 
> ## 
> 
> _Brian C. Conn_
> 
> On Mon, Mar 2, 2015 at 11:42 AM, zwegersmel notifications@github.com
> wrote:
> 
> > I wasn't sure if my adding a new event to the dev. site would be
> > reflected
> > in the final site or not, so I'm just putting in here in case!
> > 
> > Could you please add this event in the correct chronological place:
> > 
> > Author Fair Book Booth
> > Saturday, March 28 2015, 1:00-3:00pm
> > Walldorf/Dunning Rooms, Main Level
> > Plymouth District Library,
> > 223 S. Main Street, Plymouth
> > 
> > Thanks a bunch!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/TheConnMan/ZwegersMel/issues/23.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76747746
> .

## 

_Melanie M Zwegers_

Children's Writer & Illustrator

www.melaniemzwegers.com

**Comment by TheConnMan** [comment]
Same as with the dev site, just with the different URL.
http://melaniemzwegers.com/login/auth. Same username and password as before.

## 

_Brian C. Conn_

**Comment by zwegersmel** [comment]
Okay, I logged in and added the event, I'm just not sure it's added to the
real site, and I can't tell whether it will put it in chronologically or
not...

On Mon, Mar 2, 2015 at 12:05 PM, Brian Conn notifications@github.com
wrote:

> Same as with the dev site, just with the different URL.
> http://melaniemzwegers.com/login/auth. Same username and password as
> before.
> 
> ## 
> 
> _Brian C. Conn_
> 
> On Mon, Mar 2, 2015 at 11:48 AM, zwegersmel notifications@github.com
> wrote:
> 
> > Okay, how do I login in to the regular site? Sorry!
> > 
> > On Mon, Mar 2, 2015 at 11:44 AM, Brian Conn notifications@github.com
> > wrote:
> > 
> > > The dev site and the main site are two different servers now. If you
> > > want
> > > to make production changes you can add it to the non-dev site.
> > > 
> > > ## 
> > > 
> > > _Brian C. Conn_
> > > 
> > > On Mon, Mar 2, 2015 at 11:42 AM, zwegersmel notifications@github.com
> > > wrote:
> > > 
> > > > I wasn't sure if my adding a new event to the dev. site would be
> > > > reflected
> > > > in the final site or not, so I'm just putting in here in case!
> > > > 
> > > > Could you please add this event in the correct chronological place:
> > > > 
> > > > Author Fair Book Booth
> > > > Saturday, March 28 2015, 1:00-3:00pm
> > > > Walldorf/Dunning Rooms, Main Level
> > > > Plymouth District Library,
> > > > 223 S. Main Street, Plymouth
> > > > 
> > > > Thanks a bunch!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/TheConnMan/ZwegersMel/issues/23.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76747746
> > > 
> > > .
> > 
> > ## 
> > 
> > _Melanie M Zwegers_
> > 
> > Children's Writer & Illustrator
> > 
> > www.melaniemzwegers.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76748637>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76752388
> .

## 

_Melanie M Zwegers_

Children's Writer & Illustrator

www.melaniemzwegers.com

**Comment by TheConnMan** [comment]
It was correctly added, I see it in the prod site and in the correct place.

## 

_Brian C. Conn_

**Comment by zwegersmel** [comment]
Hooray!

On Mon, Mar 2, 2015 at 1:08 PM, Brian Conn notifications@github.com wrote:

> It was correctly added, I see it in the prod site and in the correct place.
> 
> ## 
> 
> _Brian C. Conn_
> 
> On Mon, Mar 2, 2015 at 12:58 PM, zwegersmel notifications@github.com
> wrote:
> 
> > Okay, I logged in and added the event, I'm just not sure it's added to
> > the
> > real site, and I can't tell whether it will put it in chronologically or
> > not...
> > 
> > On Mon, Mar 2, 2015 at 12:05 PM, Brian Conn notifications@github.com
> > wrote:
> > 
> > > Same as with the dev site, just with the different URL.
> > > http://melaniemzwegers.com/login/auth. Same username and password as
> > > before.
> > > 
> > > ## 
> > > 
> > > _Brian C. Conn_
> > > 
> > > On Mon, Mar 2, 2015 at 11:48 AM, zwegersmel notifications@github.com
> > > wrote:
> > > 
> > > > Okay, how do I login in to the regular site? Sorry!
> > > > 
> > > > On Mon, Mar 2, 2015 at 11:44 AM, Brian Conn <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > The dev site and the main site are two different servers now. If
> > > > > you
> > > > > want
> > > > > to make production changes you can add it to the non-dev site.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > _Brian C. Conn_
> > > > > 
> > > > > On Mon, Mar 2, 2015 at 11:42 AM, zwegersmel <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > I wasn't sure if my adding a new event to the dev. site would be
> > > > > > reflected
> > > > > > in the final site or not, so I'm just putting in here in case!
> > > > > > 
> > > > > > Could you please add this event in the correct chronological
> > > > > > place:
> > > > > > 
> > > > > > Author Fair Book Booth
> > > > > > Saturday, March 28 2015, 1:00-3:00pm
> > > > > > Walldorf/Dunning Rooms, Main Level
> > > > > > Plymouth District Library,
> > > > > > 223 S. Main Street, Plymouth
> > > > > > 
> > > > > > Thanks a bunch!
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/TheConnMan/ZwegersMel/issues/23.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > 
> > > > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76747746
> > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > _Melanie M Zwegers_
> > > > 
> > > > Children's Writer & Illustrator
> > > > 
> > > > www.melaniemzwegers.com
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > 
> > > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76748637
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76752388
> > > 
> > > .
> > 
> > ## 
> > 
> > _Melanie M Zwegers_
> > 
> > Children's Writer & Illustrator
> > 
> > www.melaniemzwegers.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76763244>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheConnMan/ZwegersMel/issues/23#issuecomment-76765125
> .

## 

_Melanie M Zwegers_

Children's Writer & Illustrator

www.melaniemzwegers.com
